version: "3"
services:
  app:
    container_name: "python_machine_learning"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_machine_learning
    volumes: 
        - $PWD:/project/Jupiter/src
    tty: true
